name: major 

permissions:
  contents: write
  pull-requests: write

on:
  workflow_call:
  
jobs:
  report:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Bump version
        if: github.ref == 'refs/heads/develop'
        run: |
          CURRENT_VERSION=$(git ls-remote --tags --sort="v:refname" | tail -n1 | sed 's/.*\///; s/\^{}//');
          NEXT_VERSION=$(docker run alpine/semver semver -c -i major ${CURRENT_VERSION});
          
          echo "${CURRENT_VERSION}";
          echo "${NEXT_VERSION}";
          
          git tag ${NEXT_VERSION};
          git push --tags origin;
