name: major 

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  major:
    runs-on: ubuntu-latest
    
    # Restricted to the default branch.
    # if: ${{ always() && (format('refs/heads/{0}', github.event.repository.default_branch) == github.ref) }}

    # Restriction to manual startup.
    if: ${{ github.event_name == 'workflow_dispatch' && github.actor }}
    
    defaults:
      run:
        shell: bash
      
    steps:
      - uses: actions/checkout@v3
        
      - name: Bump version
        run: |
          CURRENT_VERSION=$(git ls-remote --tags --sort="v:refname" | tail -n1 | sed 's/.*\///; s/\^{}//');
          NEXT_VERSION=$(docker run alpine/semver semver -c -i major ${CURRENT_VERSION});
          
          git tag ${NEXT_VERSION};
          git push --tags origin;
