name: minor

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      tag:
        description: "The first output string"
        value: ${{ jobs.minor.outputs.tag }}

jobs:
  minor:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
      
    outputs:
      id: tag 

    steps:
      - uses: actions/checkout@v3
        
      - name: Bump version
        run: |
          REMOTE_VERSION=$(git ls-remote --tags --sort="v:refname" | tail -n1 | sed 's/.*\///; s/\^{}//');
          CURRENT_VERSION="${REMOTE_VERSION:=0.0.0}"
          NEXT_VERSION=$(docker run alpine/semver semver -c -i minor ${CURRENT_VERSION});
          
          git tag ${NEXT_VERSION};
          git push --tags origin;
          echo "::set-output name=tag::$NEXT_VERSION"
