name: minor

permissions:
  contents: write
  pull-requests: write
  
on:
  push:
    # branches:
    #  - develop
  workflow_dispatch:
    inputs:
      semver_restriction_branch_skip:
        description: 'Must be true or false. Default is true'
        required: false
        type: boolean
        default: true
        
jobs:
  semver-minor:
    # run only on default branch, skip this restriction if `SEMVER_RESTRICTION_BRANCH_SKIP` is true
    if: ${{ always() && (format('refs/heads/{0}', github.event.repository.default_branch) == github.ref) || github.event.inputs.semver_restriction_branch_skip == 'true' }}

    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
      
    steps:
      - uses: actions/checkout@v3
        
      - name: Bump version
        run: |
          REMOTE_VERSION=$(git ls-remote --tags --sort="v:refname" | tail -n1 | sed 's/.*\///; s/\^{}//');
          CURRENT_VERSION="${REMOTE_VERSION:=0.0.0}"
          NEXT_VERSION=$(docker run alpine/semver semver -c -i minor ${CURRENT_VERSION});
          
          git tag ${NEXT_VERSION};
          git push --tags origin;
