name: patch

permissions:
  contents: write
  pull-requests: write
  
on:
  push:
#    branches:
#      - 'fix/\d+\.\d+\.x'
  workflow_call:
  
jobs:
  patch:
    runs-on: ubuntu-latest

    # Restriction to the fix branch.
    if: ${{ startsWith(github.ref, 'refs/heads/fix/') && endsWith(github.ref, '.x') }}
    
    defaults:
      run:
        shell: bash
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Bump version
        run: |
          GITHUB_REF=${GITHUB_REF//*\/}
          CURRENT_VERSION="$(git ls-remote -q --tags | awk '{ print $2}'| sort -nr | sed 's/refs\/tags\///g' | grep ${GITHUB_REF//.x} | head -n1 )";
          NEXT_VERSION=$(docker run alpine/semver semver -c -i patch ${CURRENT_VERSION});

          git tag ${NEXT_VERSION};
          git push --tags;
