name: patch

on:
  push:
    branches:
      - 'fix/\d+\.\d+\.x'
  workflow_call:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Bump version
        run: |
          GITHUB_REF=${GITHUB_REF//*\/}
          CURRENT_VERSION="$(git ls-remote -q --tags | awk '{ print $2}'| sort -nr | sed 's/refs\/tags\///g' | grep ${GITHUB_REF//.x} | head -n1 )";
          NEXT_VERSION=$(docker run alpine/semver semver -c -i patch ${CURRENT_VERSION});

          git tag ${NEXT_VERSION};
          git push --tags;
