name: 'semver'

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Semver release type (major / minor / patch)'     
        required: true

jobs:
  semver:
    runs-on: node:lts-alpine

    defaults:
      run:
        shell: sh 

    steps:
        
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Set up dependencies 
      run: |
        npm install -g semver
        apk add --no-cache git
        
    - name: semver 
      run: | 
        
        export CURRENT_VERSION=$(git describe --tags --abbrev=0)

