name: semver

on: push

permissions:
  contents: write
  
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up tools
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          
      - name: Bump version
        run: |
          CURRENT_VERSION=$(git ls-remote --tags --sort="v:refname" | tail -n1 | sed 's/.*\///; s/\^{}//');
          NEXT_VERSION=$(docker run alpine/semver semver -c -i patch ${CURRENT_VERSION});
          
          # Condition to update the NEXT_VERSION based on the branch
          if [ "${GITHUB_REF##*/}" = "${GITHUB_HEAD_REF}" ]; then
            NEXT_VERSION=$(docker run alpine/semver semver -c -i minor ${CURRENT_VERSION})
          else
            NEXT_VERSION=$(docker run alpine/semver semver -c -i patch ${CURRENT_VERSION})
          fi
        
      - name: Commit report
        run: |
          git tag ${NEXT_VERSION};
          git push --tags
