name: 'semver'

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Semver release type (major / minor / patch)'     
        #required: true

permissions:
  contents: read

jobs:
  semver:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    
      
    - name: Set up tools
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        
    - name: Bump version
      run: |
        CURRENT_VERSION=$(git ls-remote --tags --sort="v:refname" | tail -n1 | sed 's/.*\///; s/\^{}//');
        NEXT_VERSION=$(docker run alpine/semver semver -c -i patch ${CURRENT_VERSION});
        echo "Current version: ${CURRENT_VERSION}";
        echo "Next version: ${NEXT_VERSION}";

    - name: Tag and push
      run: |
        echo "${GITHUB_TOKEN}"
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "igor.sadza@gmail.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF_NAME}";
        git tag ${NEXT_VERSION};
        git push --tags
