name: 'semver'

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Semver release type (major / minor / patch)'     
        #required: true

jobs:
  semver:
    runs-on: ubuntu-latest
    env:
      GIT_API_TOKEN: ${{secrets.GIT_API_TOKEN}}
      GIT_API_USER: ${{secrets.GIT_API_USER}}    
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    
      
    - name: set-up
      run: |
        sudo apt-get update
        sudo apt-get install -y git jq

    - name: env
      run: |
        env
        echo "https://${GIT_API_USER}:${GIT_API_TOKEN}@${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
    - name: semver
      run: |
        CURRENT_VERSION="$(git ls-remote --tags --sort="v:refname" | tail -n1 | sed 's/.*\///; s/\^{}//')";
        NEXT_VERSION="$(docker run alpine/semver semver -c -i patch ${CURRENT_VERSION})";
        git checkout develop;
        git tag ${NEXT_VERSION}
        git push --tags
