name: 'semver'

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Semver release type (major / minor / patch)'     
        #required: true

jobs:
  semver:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    
      
    - name: set-up
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        git status
        
    - name: semver
      run: |
        CURRENT_VERSION="$(git ls-remote --tags --sort="v:refname" | tail -n1 | sed 's/.*\///; s/\^{}//')";
        echo DD - "${CURRENT_VERSION}"
        NEXT_VERSION="$(docker run alpine/semver semver -c -i patch ${CURRENT_VERSION})"
        echo "${NEXT_VERSION}"

        
