name: 'semver'

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Semver release type (major / minor / patch)'     
        #required: true

jobs:
  semver:
    runs-on: ubuntu-latest
    env:
      GIT_API_TOKEN: ${{secrets.GIT_API_TOKEN}}
      GIT_API_USER: ${{secrets.GIT_API_USER}}    
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    
      
    - name: Set up tools
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        
    - name: Display environment variables
      run: |
        echo "GIT_API_TOKEN=${GIT_API_TOKEN}"
        echo "GIT_API_USER=${GIT_API_USER}"      
      
    - name: Bump version
      run: |
        CURRENT_VERSION=$(git describe --tags --abbrev=0);
        NEXT_VERSION=$(docker run alpine/semver semver -c -i patch ${CURRENT_VERSION});
        echo "Current version: ${CURRENT_VERSION}";
        echo "Next version: ${NEXT_VERSION}";

    - name: Tag and push
      run: |
        GITHUB_ENDPOINT="https://${GIT_API_USER}:${GIT_API_TOKEN}@${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git";
        echo "Github endpoint: ${GITHUB_ENDPOINT}";
        git checkout main;
        git tag ${NEXT_VERSION};
        git push --tags "${GITHUB_ENDPOINT}";
