name: 'semver'

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Semver release type (major / minor / patch)'     
        required: true

jobs:
  semver:
    runs-on: ubuntu-latest
     
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Build Alpine Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --file ./build/Dockerfile --tag semver .
        
    - name: Run code on Alpine
      run: |        
        docker run semver
